// Dữ liệu địa giới hành chính Việt Nam
// Tỉnh/Thành phố và Quận/Huyện

export interface Province {
  code: string;
  name: string;
  districts: District[];
}

export interface District {
  code: string;
  name: string;
}

export const vietnamProvinces: Province[] = [
  {
    code: 'HN',
    name: 'Hà Nội',
    districts: [
      { code: 'BA_DINH', name: 'Ba Đình' },
      { code: 'HOAN_KIEM', name: 'Hoàn Kiếm' },
      { code: 'HAI_BA_TRUNG', name: 'Hai Bà Trưng' },
      { code: 'DONG_DA', name: 'Đống Đa' },
      { code: 'TAY_HO', name: 'Tây Hồ' },
      { code: 'CAU_GIAY', name: 'Cầu Giấy' },
      { code: 'THANH_XUAN', name: 'Thanh Xuân' },
      { code: 'HOANG_MAI', name: 'Hoàng Mai' },
      { code: 'LONG_BIEN', name: 'Long Biên' },
      { code: 'NAM_TU_LIEM', name: 'Nam Từ Liêm' },
      { code: 'BAC_TU_LIEM', name: 'Bắc Từ Liêm' },
      { code: 'ME_LINH', name: 'Mê Linh' },
      { code: 'HA_DONG', name: 'Hà Đông' },
      { code: 'SON_TAY', name: 'Sơn Tây' },
      { code: 'BA_VI', name: 'Ba Vì' },
      { code: 'PHUC_THO', name: 'Phúc Thọ' },
      { code: 'DAN_PHUONG', name: 'Đan Phượng' },
      { code: 'HOAI_DUC', name: 'Hoài Đức' },
      { code: 'QUOC_OAI', name: 'Quốc Oai' },
      { code: 'THACH_THAT', name: 'Thạch Thất' },
      { code: 'CHUONG_MY', name: 'Chương Mỹ' },
      { code: 'THANH_OAI', name: 'Thanh Oai' },
      { code: 'THUONG_TIN', name: 'Thường Tín' },
      { code: 'PHU_XUYEN', name: 'Phú Xuyên' },
      { code: 'UNG_HOA', name: 'Ứng Hòa' },
      { code: 'MY_DUC', name: 'Mỹ Đức' },
    ],
  },
  {
    code: 'HCM',
    name: 'Hồ Chí Minh',
    districts: [
      { code: 'QUAN_1', name: 'Quận 1' },
      { code: 'QUAN_2', name: 'Quận 2' },
      { code: 'QUAN_3', name: 'Quận 3' },
      { code: 'QUAN_4', name: 'Quận 4' },
      { code: 'QUAN_5', name: 'Quận 5' },
      { code: 'QUAN_6', name: 'Quận 6' },
      { code: 'QUAN_7', name: 'Quận 7' },
      { code: 'QUAN_8', name: 'Quận 8' },
      { code: 'QUAN_9', name: 'Quận 9' },
      { code: 'QUAN_10', name: 'Quận 10' },
      { code: 'QUAN_11', name: 'Quận 11' },
      { code: 'QUAN_12', name: 'Quận 12' },
      { code: 'BINH_TAN', name: 'Bình Tân' },
      { code: 'BINH_THANH', name: 'Bình Thạnh' },
      { code: 'GO_VAP', name: 'Gò Vấp' },
      { code: 'PHU_NHUAN', name: 'Phú Nhuận' },
      { code: 'TAN_BINH', name: 'Tân Bình' },
      { code: 'TAN_PHU', name: 'Tân Phú' },
      { code: 'THU_DUC', name: 'Thủ Đức' },
      { code: 'BINH_CHANH', name: 'Bình Chánh' },
      { code: 'CAN_GIO', name: 'Cần Giờ' },
      { code: 'CU_CHI', name: 'Củ Chi' },
      { code: 'HOC_MON', name: 'Hóc Môn' },
      { code: 'NHA_BE', name: 'Nhà Bè' },
    ],
  },
  {
    code: 'DN',
    name: 'Đà Nẵng',
    districts: [
      { code: 'HAI_CHAU', name: 'Hải Châu' },
      { code: 'THANH_KHE', name: 'Thanh Khê' },
      { code: 'SON_TRA', name: 'Sơn Trà' },
      { code: 'NGU_HANH_SON', name: 'Ngũ Hành Sơn' },
      { code: 'LIEN_CHIEU', name: 'Liên Chiểu' },
      { code: 'CAM_LE', name: 'Cẩm Lệ' },
      { code: 'HOA_VANG', name: 'Hòa Vang' },
      { code: 'HOANG_SA', name: 'Hoàng Sa' },
    ],
  },
  {
    code: 'HP',
    name: 'Hải Phòng',
    districts: [
      { code: 'HONG_BANG', name: 'Hồng Bàng' },
      { code: 'NGO_QUYEN', name: 'Ngô Quyền' },
      { code: 'LE_CHAN', name: 'Lê Chân' },
      { code: 'HAI_AN', name: 'Hải An' },
      { code: 'KIEN_AN', name: 'Kiến An' },
      { code: 'DO_SON', name: 'Đồ Sơn' },
      { code: 'DUONG_KINH', name: 'Dương Kinh' },
      { code: 'THUY_NGUYEN', name: 'Thủy Nguyên' },
      { code: 'AN_DUONG', name: 'An Dương' },
      { code: 'AN_LAO', name: 'An Lão' },
      { code: 'KIEN_THUY', name: 'Kiến Thụy' },
      { code: 'TIEN_LANG', name: 'Tiên Lãng' },
      { code: 'VINH_BAO', name: 'Vĩnh Bảo' },
      { code: 'CAT_HAI', name: 'Cát Hải' },
      { code: 'BACH_LONG_VI', name: 'Bạch Long Vĩ' },
    ],
  },
  {
    code: 'CT',
    name: 'Cần Thơ',
    districts: [
      { code: 'NINH_KIEU', name: 'Ninh Kiều' },
      { code: 'O_MON', name: 'Ô Môn' },
      { code: 'BINH_THUY', name: 'Bình Thủy' },
      { code: 'CAI_RANG', name: 'Cái Răng' },
      { code: 'THOT_NOT', name: 'Thốt Nốt' },
      { code: 'VINH_THANH', name: 'Vĩnh Thạnh' },
      { code: 'CO_DO', name: 'Cờ Đỏ' },
      { code: 'PHONG_DIEN', name: 'Phong Điền' },
      { code: 'THOI_LAI', name: 'Thới Lai' },
    ],
  },
  {
    code: 'AG',
    name: 'An Giang',
    districts: [
      { code: 'LONG_XUYEN', name: 'Long Xuyên' },
      { code: 'CHAU_DOC', name: 'Châu Đốc' },
      { code: 'AN_PHU', name: 'An Phú' },
      { code: 'CHAU_PHU', name: 'Châu Phú' },
      { code: 'CHAU_THANH', name: 'Châu Thành' },
      { code: 'CHO_MOI', name: 'Chợ Mới' },
      { code: 'PHU_TAN', name: 'Phú Tân' },
      { code: 'THOAI_SON', name: 'Thoại Sơn' },
      { code: 'TINH_BIEN', name: 'Tịnh Biên' },
      { code: 'TRI_TON', name: 'Tri Tôn' },
    ],
  },
  {
    code: 'BR-VT',
    name: 'Bà Rịa - Vũng Tàu',
    districts: [
      { code: 'VUNG_TAU', name: 'Vũng Tàu' },
      { code: 'BA_RIA', name: 'Bà Rịa' },
      { code: 'CHAU_DUC', name: 'Châu Đức' },
      { code: 'CON_DAO', name: 'Côn Đảo' },
      { code: 'DAT_DO', name: 'Đất Đỏ' },
      { code: 'LONG_DIEN', name: 'Long Điền' },
      { code: 'TAN_THANH', name: 'Tân Thành' },
      { code: 'XUYEN_MOC', name: 'Xuyên Mộc' },
    ],
  },
  {
    code: 'BL',
    name: 'Bạc Liêu',
    districts: [
      { code: 'BAC_LIEU', name: 'Bạc Liêu' },
      { code: 'HONG_DAN', name: 'Hồng Dân' },
      { code: 'PHUOC_LONG', name: 'Phước Long' },
      { code: 'VINH_LOI', name: 'Vĩnh Lợi' },
      { code: 'GIA_RAI', name: 'Giá Rai' },
      { code: 'DONG_HAI', name: 'Đông Hải' },
      { code: 'HOA_BINH', name: 'Hoà Bình' },
    ],
  },
  {
    code: 'BK',
    name: 'Bắc Kạn',
    districts: [
      { code: 'BAC_KAN', name: 'Bắc Kạn' },
      { code: 'PAC_NAM', name: 'Pác Nặm' },
      { code: 'BA_BE', name: 'Ba Bể' },
      { code: 'NGAN_SON', name: 'Ngân Sơn' },
      { code: 'BACH_THONG', name: 'Bạch Thông' },
      { code: 'CHO_DON', name: 'Chợ Đồn' },
      { code: 'CHO_MOI', name: 'Chợ Mới' },
      { code: 'NA_RI', name: 'Na Rì' },
    ],
  },
  {
    code: 'BG',
    name: 'Bắc Giang',
    districts: [
      { code: 'BAC_GIANG', name: 'Bắc Giang' },
      { code: 'YEN_THE', name: 'Yên Thế' },
      { code: 'TAN_YEN', name: 'Tân Yên' },
      { code: 'LANG_GIANG', name: 'Lạng Giang' },
      { code: 'LUC_NAM', name: 'Lục Nam' },
      { code: 'LUC_NGAN', name: 'Lục Ngạn' },
      { code: 'SON_DONG', name: 'Sơn Động' },
      { code: 'YEN_DUNG', name: 'Yên Dũng' },
      { code: 'VIET_YEN', name: 'Việt Yên' },
      { code: 'HIEP_HOA', name: 'Hiệp Hòa' },
    ],
  },
  {
    code: 'BN',
    name: 'Bắc Ninh',
    districts: [
      { code: 'BAC_NINH', name: 'Bắc Ninh' },
      { code: 'YEN_PHONG', name: 'Yên Phong' },
      { code: 'QUE_VO', name: 'Quế Võ' },
      { code: 'TIEN_DU', name: 'Tiên Du' },
      { code: 'TU_SON', name: 'Từ Sơn' },
      { code: 'THUAN_THANH', name: 'Thuận Thành' },
      { code: 'GIA_BINH', name: 'Gia Bình' },
      { code: 'LUONG_TAI', name: 'Lương Tài' },
    ],
  },
  {
    code: 'BT',
    name: 'Bến Tre',
    districts: [
      { code: 'BEN_TRE', name: 'Bến Tre' },
      { code: 'CHA_THANH', name: 'Châu Thành' },
      { code: 'CHO_LACH', name: 'Chợ Lách' },
      { code: 'MO_CAY_NAM', name: 'Mỏ Cày Nam' },
      { code: 'MO_CAY_BAC', name: 'Mỏ Cày Bắc' },
      { code: 'GIONG_TROM', name: 'Giồng Trôm' },
      { code: 'BINH_DAI', name: 'Bình Đại' },
      { code: 'BA_TRI', name: 'Ba Tri' },
      { code: 'THANH_PHU', name: 'Thạnh Phú' },
    ],
  },
  {
    code: 'BD',
    name: 'Bình Định',
    districts: [
      { code: 'QUY_NHON', name: 'Quy Nhon' },
      { code: 'AN_LAO', name: 'An Lão' },
      { code: 'HOAI_AN', name: 'Hoài Ân' },
      { code: 'HOAI_NHON', name: 'Hoài Nhơn' },
      { code: 'PHU_MY', name: 'Phù Mỹ' },
      { code: 'PHU_CAT', name: 'Phù Cát' },
      { code: 'VINH_THANH', name: 'Vĩnh Thạnh' },
      { code: 'TAY_SON', name: 'Tây Sơn' },
      { code: 'TUY_PHUOC', name: 'Tuy Phước' },
      { code: 'VAN_CANH', name: 'Vân Canh' },
    ],
  },
  {
    code: 'BP',
    name: 'Bình Phước',
    districts: [
      { code: 'DONG_XOAI', name: 'Đồng Xoài' },
      { code: 'BINH_LONG', name: 'Bình Long' },
      { code: 'BUX_DANG', name: 'Bù Đăng' },
      { code: 'BUX_GIA_MAP', name: 'Bù Gia Mập' },
      { code: 'BUX_DOP', name: 'Bù Đốp' },
      { code: 'CHON_THANH', name: 'Chơn Thành' },
      { code: 'DONG_PHU', name: 'Đồng Phú' },
      { code: 'HON_QUAN', name: 'Hớn Quản' },
      { code: 'LOC_NINH', name: 'Lộc Ninh' },
    ],
  },
  {
    code: 'BTH',
    name: 'Bình Thuận',
    districts: [
      { code: 'PHAN_THIET', name: 'Phan Thiết' },
      { code: 'LA_GI', name: 'La Gi' },
      { code: 'TUYEN_QUANG', name: 'Tuyến Quang' },
      { code: 'BAC_BINH', name: 'Bắc Bình' },
      { code: 'HAM_THUAN_BAC', name: 'Hàm Thuận Bắc' },
      { code: 'HAM_THUAN_NAM', name: 'Hàm Thuận Nam' },
      { code: 'HAM_TAN', name: 'Hàm Tân' },
      { code: 'PHU_QUI', name: 'Phú Quí' },
      { code: 'TANH_LINH', name: 'Tánh Linh' },
    ],
  },
  {
    code: 'CM',
    name: 'Cà Mau',
    districts: [
      { code: 'CA_MAU', name: 'Cà Mau' },
      { code: 'CAI_NUOC', name: 'Cái Nước' },
      { code: 'DAM_DOI', name: 'Đầm Dơi' },
      { code: 'NAM_CAN', name: 'Năm Căn' },
      { code: 'NGOC_HIEN', name: 'Ngọc Hiển' },
      { code: 'PHU_TAN', name: 'Phú Tân' },
      { code: 'THOI_BINH', name: 'Thới Bình' },
      { code: 'TRAN_VAN_THOI', name: 'Trần Văn Thời' },
      { code: 'UMINH', name: 'U Minh' },
    ],
  },
  {
    code: 'CB',
    name: 'Cao Bằng',
    districts: [
      { code: 'CAO_BANG', name: 'Cao Bằng' },
      { code: 'BAO_LAC', name: 'Bảo Lạc' },
      { code: 'BAO_LAM', name: 'Bảo Lâm' },
      { code: 'HA_QUANG', name: 'Hà Quảng' },
      { code: 'HOA_AN', name: 'Hòa An' },
      { code: 'NGUYEN_BINH', name: 'Nguyên Bình' },
      { code: 'QUANG_UYEN', name: 'Quảng Uyên' },
      { code: 'THACH_AN', name: 'Thạch An' },
      { code: 'TRUNG_KHANH', name: 'Trùng Khánh' },
    ],
  },
  {
    code: 'DL',
    name: 'Đắk Lắk',
    districts: [
      { code: 'BUON_MA_THUOT', name: 'Buôn Ma Thuột' },
      { code: 'BUON_HO', name: 'Buôn Hồ' },
      { code: 'CU_KBANG', name: 'Cư K\'bang' },
      { code: 'CU_MGAR', name: 'Cư M\'gar' },
      { code: 'EA_HLEO', name: 'Ea H\'leo' },
      { code: 'EA_KAR', name: 'Ea Kar' },
      { code: 'EA_SUP', name: 'Ea Súp' },
      { code: 'KRONG_ANA', name: 'Krông A Na' },
      { code: 'KBUK', name: 'Krông Bông' },
      { code: 'KBUK_PAK', name: 'Krông Búk' },
      { code: 'KNA', name: 'Krông Năng' },
      { code: 'KPAK', name: 'Krông Pắk' },
      { code: 'MDRAK', name: 'M\'Đrắk' },
    ],
  },
  {
    code: 'DG',
    name: 'Đắk Nông',
    districts: [
      { code: 'GIA_NGHIA', name: 'Gia Nghĩa' },
      { code: 'CU_JUT', name: 'Cư Jút' },
      { code: 'DAK_GLONG', name: 'Đắk Glong' },
      { code: 'DAK_MIL', name: 'Đắk Mil' },
      { code: 'DAK_RLAP', name: 'Đắk R\'Lấp' },
      { code: 'DAK_SONG', name: 'Đắk Song' },
      { code: 'KRONG_NO', name: 'Krông Nô' },
      { code: 'TUY_DUC', name: 'Tuy Đức' },
    ],
  },
  {
    code: 'DB',
    name: 'Điện Biên',
    districts: [
      { code: 'DIEN_BIEN_PHU', name: 'Điện Biên Phủ' },
      { code: 'MUONG_LAY', name: 'Mường Lay' },
      { code: 'MUONG_ANG', name: 'Mường Ảng' },
      { code: 'MUONG_CHA', name: 'Mường Chà' },
      { code: 'MUONG_NHE', name: 'Mường Nhé' },
      { code: 'MUONG_TRA', name: 'Mường Tra' },
      { code: 'NAM_PO', name: 'Nậm Pồ' },
      { code: 'TUAN_GIAO', name: 'Tuần Giáo' },
      { code: 'TUAN_CHAU', name: 'Tủa Chùa' },
    ],
  },
  {
    code: 'DNA',
    name: 'Đồng Nai',
    districts: [
      { code: 'BIEN_HOA', name: 'Biên Hòa' },
      { code: 'LONG_KHANH', name: 'Long Khánh' },
      { code: 'CAM_MY', name: 'Cẩm Mỹ' },
      { code: 'DINH_QUAN', name: 'Định Quán' },
      { code: 'LONG_THANH', name: 'Long Thành' },
      { code: 'NHON_TRACH', name: 'Nhơn Trạch' },
      { code: 'TAN_PHU', name: 'Tân Phú' },
      { code: 'THONG_NHAT', name: 'Thống Nhất' },
      { code: 'VINH_CUU', name: 'Vĩnh Cửu' },
      { code: 'XUAN_LOC', name: 'Xuân Lộc' },
      { code: 'TRANG_BOM', name: 'Trảng Bom' },
    ],
  },
  {
    code: 'DT',
    name: 'Đồng Tháp',
    districts: [
      { code: 'CAO_LANH', name: 'Cao Lãnh' },
      { code: 'SA_DEC', name: 'Sa Đéc' },
      { code: 'TAN_HONG', name: 'Tân Hồng' },
      { code: 'TAN_HUNG', name: 'Tân Hưng' },
      { code: 'TAN_THANH', name: 'Tân Thành' },
      { code: 'THAP_MUOI', name: 'Tháp Mười' },
      { code: 'HONG_NGU', name: 'Hồng Ngự' },
      { code: 'TAM_NONG', name: 'Tam Nông' },
      { code: 'THANH_BINH', name: 'Thanh Bình' },
      { code: 'LAP_VO', name: 'Lấp Vò' },
      { code: 'LAI_VUNG', name: 'Lai Vung' },
      { code: 'CHA_THANH', name: 'Châu Thành' },
    ],
  },
  {
    code: 'GL',
    name: 'Gia Lai',
    districts: [
      { code: 'PLEIKU', name: 'Pleiku' },
      { code: 'AN_KHE', name: 'An Khê' },
      { code: 'AYUN_PA', name: 'Ayun Pa' },
      { code: 'KBANG', name: 'KBang' },
      { code: 'CHU_PAH', name: 'Chư Păh' },
      { code: 'CHU_PRONG', name: 'Chư Prông' },
      { code: 'CHU_SEH', name: 'Chư Sê' },
      { code: 'DAK_DOA', name: 'Đăk Đoa' },
      { code: 'DAK_PO', name: 'Đăk Pơ' },
      { code: 'DERANG', name: 'Đức Cơ' },
      { code: 'IA_GRAI', name: 'Ia Grai' },
      { code: 'IA_PA', name: 'Ia Pa' },
      { code: 'KONG_CHRO', name: 'Kông Chro' },
      { code: 'KRONG_PA', name: 'Krông Pa' },
      { code: 'MANG_YANG', name: 'Mang Yang' },
      { code: 'PHU_THIEN', name: 'Phú Thiện' },
    ],
  },
  {
    code: 'HG',
    name: 'Hà Giang',
    districts: [
      { code: 'HA_GIANG', name: 'Hà Giang' },
      { code: 'BAC_ME', name: 'Bắc Mê' },
      { code: 'BAC_QUANG', name: 'Bắc Quang' },
      { code: 'DONG_VAN', name: 'Đồng Văn' },
      { code: 'HOANG_SU_PHI', name: 'Hoàng Su Phì' },
      { code: 'MEO_VAC', name: 'Mèo Vạc' },
      { code: 'QUAN_BA', name: 'Quản Bạ' },
      { code: 'QUANG_BINH', name: 'Quang Bình' },
      { code: 'VI_XUYEN', name: 'Vị Xuyên' },
      { code: 'XIN_MAN', name: 'Xín Mần' },
      { code: 'YEN_MINH', name: 'Yên Minh' },
    ],
  },
  {
    code: 'HD',
    name: 'Hà Nam',
    districts: [
      { code: 'PHU_LY', name: 'Phủ Lý' },
      { code: 'DUY_TIEN', name: 'Duy Tiên' },
      { code: 'KIM_BANG', name: 'Kim Bảng' },
      { code: 'LY_NHAN', name: 'Lý Nhân' },
      { code: 'THANH_LIEM', name: 'Thanh Liêm' },
      { code: 'BINH_LUC', name: 'Bình Lục' },
    ],
  },
  {
    code: 'HY',
    name: 'Hưng Yên',
    districts: [
      { code: 'HUNG_YEN', name: 'Hưng Yên' },
      { code: 'MY_HAO', name: 'Mỹ Hào' },
      { code: 'AN_THI', name: 'Ân Thi' },
      { code: 'KHOAI_CHAU', name: 'Khoái Châu' },
      { code: 'KIM_DONG', name: 'Kim Động' },
      { code: 'PHU_CU', name: 'Phù Cừ' },
      { code: 'TIEN_LU', name: 'Tiên Lữ' },
      { code: 'VAN_GIANG', name: 'Văn Giang' },
      { code: 'VAN_LAM', name: 'Văn Lâm' },
      { code: 'YEN_MY', name: 'Yên Mỹ' },
    ],
  },
  {
    code: 'KH',
    name: 'Khánh Hòa',
    districts: [
      { code: 'NHA_TRANG', name: 'Nha Trang' },
      { code: 'CAM_RANH', name: 'Cam Ranh' },
      { code: 'CAM_LAM', name: 'Cam Lâm' },
      { code: 'DIEN_KHANH', name: 'Diên Khánh' },
      { code: 'KHANH_SON', name: 'Khánh Sơn' },
      { code: 'KHANH_VINH', name: 'Khánh Vĩnh' },
      { code: 'NINH_HOA', name: 'Ninh Hòa' },
      { code: 'TRUONG_SA', name: 'Trường Sa' },
      { code: 'VAN_NINH', name: 'Vạn Ninh' },
    ],
  },
  {
    code: 'KG',
    name: 'Kiên Giang',
    districts: [
      { code: 'RACH_GIA', name: 'Rạch Giá' },
      { code: 'HA_TIEN', name: 'Hà Tiên' },
      { code: 'AN_MINH', name: 'An Minh' },
      { code: 'AN_BIEN', name: 'An Biên' },
      { code: 'CHA_THANH', name: 'Châu Thành' },
      { code: 'GIANG_THANH', name: 'Giàng Thành' },
      { code: 'GIONG_RIENG', name: 'Giồng Riềng' },
      { code: 'GO_QUAO', name: 'Gò Quao' },
      { code: 'HON_DAT', name: 'Hòn Đất' },
      { code: 'KIEN_HAI', name: 'Kiên Hải' },
      { code: 'KIEN_LUONG', name: 'Kiên Lương' },
      { code: 'PHU_QUOC', name: 'Phú Quốc' },
      { code: 'TAN_HIEP', name: 'Tân Hiệp' },
      { code: 'U_MINH_THUONG', name: 'U Minh Thượng' },
      { code: 'VINH_THUAN', name: 'Vĩnh Thuận' },
    ],
  },
  {
    code: 'LC',
    name: 'Lào Cai',
    districts: [
      { code: 'LAO_CAI', name: 'Lào Cai' },
      { code: 'BAT_XAT', name: 'Bát Xát' },
      { code: 'BAO_THANG', name: 'Bảo Thắng' },
      { code: 'BAO_YEN', name: 'Bảo Yên' },
      { code: 'BAC_HA', name: 'Bắc Hà' },
      { code: 'MUONG_KHUONG', name: 'Mường Khương' },
      { code: 'SA_PA', name: 'Sa Pa' },
      { code: 'SI_MA_CAI', name: 'Si Ma Cai' },
      { code: 'VAN_BAN', name: 'Văn Bàn' },
    ],
  },
  {
    code: 'LD',
    name: 'Lâm Đồng',
    districts: [
      { code: 'DA_LAT', name: 'Đà Lạt' },
      { code: 'BAO_LOC', name: 'Bảo Lộc' },
      { code: 'BAO_LAM', name: 'Bảo Lâm' },
      { code: 'CAT_TIEN', name: 'Cát Tiên' },
      { code: 'DA_HUOAI', name: 'Đạ Huoai' },
      { code: 'DA_TEH', name: 'Đạ Tẻh' },
      { code: 'DAM_RONG', name: 'Đam Rông' },
      { code: 'DON_DUONG', name: 'Đơn Dương' },
      { code: 'DUC_TRONG', name: 'Đức Trọng' },
      { code: 'LAC_DUONG', name: 'Lạc Dương' },
      { code: 'LAM_HA', name: 'Lâm Hà' },
    ],
  },
  {
    code: 'LS',
    name: 'Lạng Sơn',
    districts: [
      { code: 'LANG_SON', name: 'Lạng Sơn' },
      { code: 'BAC_SON', name: 'Bắc Sơn' },
      { code: 'BINH_GIA', name: 'Bình Gia' },
      { code: 'CAO_LOC', name: 'Cao Lộc' },
      { code: 'CHI_LANG', name: 'Chi Lăng' },
      { code: 'DINH_LAP', name: 'Đình Lập' },
      { code: 'HUU_LUNG', name: 'Hữu Lũng' },
      { code: 'LOC_BINH', name: 'Lộc Bình' },
      { code: 'TRANG_DINH', name: 'Tràng Định' },
      { code: 'VAN_LANG', name: 'Văn Lãng' },
      { code: 'VAN_QUAN', name: 'Văn Quan' },
    ],
  },
  {
    code: 'LB',
    name: 'Lai Châu',
    districts: [
      { code: 'LAI_CHAU', name: 'Lai Châu' },
      { code: 'MUONG_TE', name: 'Mường Tè' },
      { code: 'NAM_NHUN', name: 'Nậm Nhùn' },
      { code: 'PHONG_THO', name: 'Phong Thổ' },
      { code: 'SIN_HO', name: 'Sìn Hồ' },
      { code: 'TAM_DUONG', name: 'Tam Đường' },
      { code: 'TAN_UYEN', name: 'Tân Uyên' },
      { code: 'THAN_UYEN', name: 'Than Uyên' },
    ],
  },
  {
    code: 'ND',
    name: 'Nghệ An',
    districts: [
      { code: 'VINH', name: 'Vinh' },
      { code: 'CUA_LO', name: 'Cửa Lò' },
      { code: 'THAI_HOA', name: 'Thái Hòa' },
      { code: 'HOANG_MAI', name: 'Hoàng Mai' },
      { code: 'ANH_SON', name: 'Anh Sơn' },
      { code: 'CON_CUONG', name: 'Con Cuông' },
      { code: 'DIEN_CHAU', name: 'Diễn Châu' },
      { code: 'DO_LUONG', name: 'Đô Lương' },
      { code: 'HUNG_NGUYEN', name: 'Hưng Nguyên' },
      { code: 'KY_SON', name: 'Kỳ Sơn' },
      { code: 'NAM_DAN', name: 'Nam Đàn' },
      { code: 'NGHI_LOC', name: 'Nghi Lộc' },
      { code: 'NGHI_DUC', name: 'Nghĩa Đàn' },
      { code: 'QUE_PHONG', name: 'Quế Phong' },
      { code: 'QUY_CHAU', name: 'Quỳ Châu' },
      { code: 'QUY_HOP', name: 'Quỳ Hợp' },
      { code: 'QUYNH_LUU', name: 'Quỳnh Lưu' },
      { code: 'TAN_KY', name: 'Tân Kỳ' },
      { code: 'THANH_CHUONG', name: 'Thanh Chương' },
      { code: 'TUONG_DUONG', name: 'Tương Dương' },
      { code: 'YEN_THANH', name: 'Yên Thành' },
    ],
  },
  {
    code: 'NB',
    name: 'Ninh Bình',
    districts: [
      { code: 'NINH_BINH', name: 'Ninh Bình' },
      { code: 'TAM_DIEP', name: 'Tam Điệp' },
      { code: 'GIA_VIEN', name: 'Gia Viễn' },
      { code: 'HOA_LU', name: 'Hoa Lư' },
      { code: 'KIM_SON', name: 'Kim Sơn' },
      { code: 'Nho_QUAN', name: 'Nho Quan' },
      { code: 'YEN_KHANH', name: 'Yên Khánh' },
      { code: 'YEN_MO', name: 'Yên Mô' },
    ],
  },
  {
    code: 'NT',
    name: 'Ninh Thuận',
    districts: [
      { code: 'PHAN_RANG_THAP_CHAM', name: 'Phan Rang-Tháp Chàm' },
      { code: 'BAC_AI', name: 'Bác Ái' },
      { code: 'NINH_HAI', name: 'Ninh Hải' },
      { code: 'NINH_PHƯỚC', name: 'Ninh Phước' },
      { code: 'NINH_SON', name: 'Ninh Sơn' },
      { code: 'THUAN_BAC', name: 'Thuận Bắc' },
      { code: 'THUAN_NAM', name: 'Thuận Nam' },
    ],
  },
  {
    code: 'PT',
    name: 'Phú Thọ',
    districts: [
      { code: 'VIET_TRI', name: 'Việt Trì' },
      { code: 'PHU_THO', name: 'Phú Thọ' },
      { code: 'CAM_KHE', name: 'Cẩm Khê' },
      { code: 'DOAN_HUNG', name: 'Đoan Hùng' },
      { code: 'HA_HOA', name: 'Hạ Hòa' },
      { code: 'LAM_THAO', name: 'Lâm Thao' },
      { code: 'PHU_NINH', name: 'Phù Ninh' },
      { code: 'TAM_NONG', name: 'Tam Nông' },
      { code: 'TAN_SON', name: 'Tân Sơn' },
      { code: 'THANH_BA', name: 'Thanh Ba' },
      { code: 'THANH_SON', name: 'Thanh Sơn' },
      { code: 'THANH_THUY', name: 'Thanh Thủy' },
      { code: 'YEN_LAP', name: 'Yên Lập' },
    ],
  },
  {
    code: 'PY',
    name: 'Phú Yên',
    districts: [
      { code: 'TUY_HOA', name: 'Tuy Hòa' },
      { code: 'SONG_HINH', name: 'Sông Hinh' },
      { code: 'SON_HOA', name: 'Sơn Hòa' },
      { code: 'PHU_HOA', name: 'Phú Hòa' },
      { code: 'TAY_HOA', name: 'Tây Hòa' },
      { code: 'TUY_AN', name: 'Tuy An' },
      { code: 'DONG_XUAN', name: 'Đồng Xuân' },
    ],
  },
  {
    code: 'QB',
    name: 'Quảng Bình',
    districts: [
      { code: 'DONG_HOI', name: 'Đồng Hới' },
      { code: 'BA_TRACH', name: 'Bố Trạch' },
      { code: 'LE_THUY', name: 'Lệ Thủy' },
      { code: 'MINH_HOA', name: 'Minh Hóa' },
      { code: 'QUANG_NINH', name: 'Quảng Ninh' },
      { code: 'QUANG_TRACH', name: 'Quảng Trạch' },
      { code: 'TUYEN_HOA', name: 'Tuyên Hóa' },
    ],
  },
  {
    code: 'QM',
    name: 'Quảng Nam',
    districts: [
      { code: 'TAM_KY', name: 'Tam Kỳ' },
      { code: 'HOI_AN', name: 'Hội An' },
      { code: 'BAC_TRA_MY', name: 'Bắc Trà My' },
      { code: 'DAI_LOC', name: 'Đại Lộc' },
      { code: 'DONG_GIANG', name: 'Đông Giang' },
      { code: 'DUY_XUYEN', name: 'Duy Xuyên' },
      { code: 'HIEP_DUC', name: 'Hiệp Đức' },
      { code: 'NAM_GIANG', name: 'Nam Giang' },
      { code: 'NAM_TRA_MY', name: 'Nam Trà My' },
      { code: 'PHUOC_SON', name: 'Phước Sơn' },
      { code: 'PHU_NINH', name: 'Phú Ninh' },
      { code: 'QUE_SON', name: 'Quế Sơn' },
      { code: 'TAY_GIANG', name: 'Tây Giang' },
      { code: 'THANG_BINH', name: 'Thăng Bình' },
      { code: 'TIEN_PHUOC', name: 'Tiên Phước' },
    ],
  },
  {
    code: 'QG',
    name: 'Quảng Ngãi',
    districts: [
      { code: 'QUANG_NGAI', name: 'Quảng Ngãi' },
      { code: 'BA_TO', name: 'Ba Tơ' },
      { code: 'BINH_SON', name: 'Bình Sơn' },
      { code: 'DUC_PHO', name: 'Đức Phổ' },
      { code: 'LY_SON', name: 'Lý Sơn' },
      { code: 'MINH_LONG', name: 'Minh Long' },
      { code: 'MO_DUC', name: 'Mộ Đức' },
      { code: 'NGHIA_HANH', name: 'Nghĩa Hành' },
      { code: 'SON_HA', name: 'Sơn Hà' },
      { code: 'SON_TINH', name: 'Sơn Tịnh' },
      { code: 'SON_TAY', name: 'Sơn Tây' },
      { code: 'TAY_TRA', name: 'Tây Trà' },
      { code: 'TRA_BONG', name: 'Trà Bồng' },
      { code: 'TU_NGHIA', name: 'Tư Nghĩa' },
    ],
  },
  {
    code: 'QN',
    name: 'Quảng Ninh',
    districts: [
      { code: 'HA_LONG', name: 'Hạ Long' },
      { code: 'MONG_CAI', name: 'Móng Cái' },
      { code: 'CAM_PHA', name: 'Cẩm Phả' },
      { code: 'UONG_BI', name: 'Uông Bí' },
      { code: 'BINH_LIEU', name: 'Bình Liêu' },
      { code: 'CAO_BANG', name: 'Cô Tô' },
      { code: 'DAM_HA', name: 'Đầm Hà' },
      { code: 'DONG_TRIEU', name: 'Đông Triều' },
      { code: 'HAI_HA', name: 'Hải Hà' },
      { code: 'HOANH_BO', name: 'Hoành Bồ' },
      { code: 'QUANG_YEN', name: 'Quảng Yên' },
      { code: 'TIEN_YEN', name: 'Tiên Yên' },
      { code: 'VAN_DON', name: 'Vân Đồn' },
    ],
  },
  {
    code: 'QT',
    name: 'Quảng Trị',
    districts: [
      { code: 'DONG_HA', name: 'Đông Hà' },
      { code: 'QUANG_TRI', name: 'Quảng Trị' },
      { code: 'CAM_LO', name: 'Cam Lộ' },
      { code: 'CON_CO', name: 'Cồn Cỏ' },
      { code: 'DA_KRONG', name: 'Đa Krông' },
      { code: 'GIO_LINH', name: 'Gio Linh' },
      { code: 'HAI_LANG', name: 'Hải Lăng' },
      { code: 'HUONG_HOA', name: 'Hướng Hóa' },
      { code: 'TRIEU_PHONG', name: 'Triệu Phong' },
      { code: 'VINH_LINH', name: 'Vĩnh Linh' },
    ],
  },
  {
    code: 'ST',
    name: 'Sóc Trăng',
    districts: [
      { code: 'SOC_TRANG', name: 'Sóc Trăng' },
      { code: 'CHA_THANH', name: 'Châu Thành' },
      { code: 'CU_LAO_DUNG', name: 'Cù Lao Dung' },
      { code: 'KE_SACH', name: 'Kế Sách' },
      { code: 'LONG_PHU', name: 'Long Phú' },
      { code: 'MY_TU', name: 'Mỹ Tú' },
      { code: 'MY_XUYEN', name: 'Mỹ Xuyên' },
      { code: 'NGA_NAM', name: 'Ngã Năm' },
      { code: 'THANH_TRI', name: 'Thạnh Trị' },
      { code: 'TRAN_DE', name: 'Trần Đề' },
      { code: 'VINH_CHAU', name: 'Vĩnh Châu' },
    ],
  },
  {
    code: 'SL',
    name: 'Sơn La',
    districts: [
      { code: 'SON_LA', name: 'Sơn La' },
      { code: 'MAI_SON', name: 'Mai Sơn' },
      { code: 'MUONG_LA', name: 'Mường La' },
      { code: 'MUONG_CHA', name: 'Mường Chà' },
      { code: 'MUONG_LAY', name: 'Mường Lay' },
      { code: 'MUONG_NHE', name: 'Mường Nhé' },
      { code: 'MUONG_TRA', name: 'Mường Tra' },
      { code: 'PHU_YEN', name: 'Phù Yên' },
      { code: 'QUYNH_NHAI', name: 'Quỳnh Nhai' },
      { code: 'SONG_MA', name: 'Sông Mã' },
      { code: 'SOP_COP', name: 'Sốp Cộp' },
      { code: 'THUAN_CHAU', name: 'Thuận Châu' },
      { code: 'VAN_HO', name: 'Vân Hồ' },
      { code: 'YEN_CHAU', name: 'Yên Châu' },
    ],
  },
  {
    code: 'TN',
    name: 'Tây Ninh',
    districts: [
      { code: 'TAY_NINH', name: 'Tây Ninh' },
      { code: 'BEN_CAU', name: 'Bến Cầu' },
      { code: 'CHAU_THANH', name: 'Châu Thành' },
      { code: 'DUONG_MINH_CHAU', name: 'Dương Minh Châu' },
      { code: 'GO_DAU', name: 'Gò Dầu' },
      { code: 'HOA_THANH', name: 'Hòa Thành' },
      { code: 'TAN_BIEN', name: 'Tân Biên' },
      { code: 'TAN_CHAU', name: 'Tân Châu' },
      { code: 'TRANG_BANG', name: 'Trảng Bàng' },
    ],
  },
  {
    code: 'TB',
    name: 'Thái Bình',
    districts: [
      { code: 'THAI_BINH', name: 'Thái Bình' },
      { code: 'DONG_HUNG', name: 'Đông Hưng' },
      { code: 'HUUNG_HA', name: 'Hưng Hà' },
      { code: 'KIEN_XUONG', name: 'Kiến Xương' },
      { code: 'QUYNH_PHU', name: 'Quỳnh Phụ' },
      { code: 'THAI_THUY', name: 'Thái Thụy' },
      { code: 'TIEN_HAI', name: 'Tiền Hải' },
      { code: 'VU_THU', name: 'Vũ Thư' },
    ],
  },
  {
    code: 'TY',
    name: 'Thái Nguyên',
    districts: [
      { code: 'THAI_NGUYEN', name: 'Thái Nguyên' },
      { code: 'SONG_CONG', name: 'Sông Công' },
      { code: 'DINH_HOA', name: 'Định Hóa' },
      { code: 'DAI_TU', name: 'Đại Từ' },
      { code: 'DONG_HY', name: 'Đồng Hỷ' },
      { code: 'PHU_BINH', name: 'Phú Bình' },
      { code: 'PHU_LUONG', name: 'Phú Lương' },
      { code: 'VO_NHAI', name: 'Võ Nhai' },
    ],
  },
  {
    code: 'TH',
    name: 'Thanh Hóa',
    districts: [
      { code: 'THANH_HOA', name: 'Thanh Hóa' },
      { code: 'BIM_SON', name: 'Bỉm Sơn' },
      { code: 'SAM_SON', name: 'Sầm Sơn' },
      { code: 'MUONG_LAT', name: 'Mường Lát' },
      { code: 'QUAN_HOA', name: 'Quan Hóa' },
      { code: 'BA_THUOC', name: 'Bá Thước' },
      { code: 'QUAN_SON', name: 'Quan Sơn' },
      { code: 'LANG_CHANH', name: 'Lang Chánh' },
      { code: 'NGOC_LAC', name: 'Ngọc Lặc' },
      { code: 'CAM_THUY', name: 'Cẩm Thủy' },
      { code: 'THACH_THANH', name: 'Thạch Thành' },
      { code: 'HA_TRUNG', name: 'Hà Trung' },
      { code: 'VINH_LOC', name: 'Vĩnh Lộc' },
      { code: 'YEN_DINH', name: 'Yên Định' },
      { code: 'THO_XUAN', name: 'Thọ Xuân' },
      { code: 'THUONG_XUAN', name: 'Thường Xuân' },
      { code: 'TRIEU_SON', name: 'Triệu Sơn' },
      { code: 'THIEU_HOA', name: 'Thiệu Hóa' },
      { code: 'HOANG_HOA', name: 'Hoằng Hóa' },
      { code: 'HAU_LOC', name: 'Hậu Lộc' },
      { code: 'NGA_SON', name: 'Nga Sơn' },
      { code: 'NHU_XUAN', name: 'Như Xuân' },
      { code: 'NHU_THANH', name: 'Như Thanh' },
      { code: 'NOONG_CONG', name: 'Nông Cống' },
      { code: 'DONG_SON', name: 'Đông Sơn' },
      { code: 'QUANG_XUONG', name: 'Quảng Xương' },
      { code: 'TINH_GIA', name: 'Tĩnh Gia' },
    ],
  },
  {
    code: 'HUE',
    name: 'Thừa Thiên Huế',
    districts: [
      { code: 'HUE', name: 'Huế' },
      { code: 'HƯƠNG_THUY', name: 'Hương Thủy' },
      { code: 'HƯƠNG_TRA', name: 'Hương Trà' },
      { code: 'A_LUOI', name: 'A Lưới' },
      { code: 'NAM_DONG', name: 'Nam Đông' },
      { code: 'PHONG_DIEN', name: 'Phong Điền' },
      { code: 'PHU_LOC', name: 'Phú Lộc' },
      { code: 'PHU_VANG', name: 'Phú Vang' },
      { code: 'QUANG_DIEN', name: 'Quảng Điền' },
    ],
  },
  {
    code: 'TG',
    name: 'Tiền Giang',
    districts: [
      { code: 'MY_THO', name: 'Mỹ Tho' },
      { code: 'GO_CONG', name: 'Gò Công' },
      { code: 'CAI_BE', name: 'Cái Bè' },
      { code: 'CAI_LAY', name: 'Cái Lậy' },
      { code: 'CHA_THANH', name: 'Châu Thành' },
      { code: 'CHO_GAO', name: 'Chợ Gạo' },
      { code: 'GO_CONG_TAY', name: 'Gò Công Tây' },
      { code: 'GO_CONG_DONG', name: 'Gò Công Đông' },
      { code: 'TAN_PHU_DONG', name: 'Tân Phú Đông' },
      { code: 'TAN_PHUOC', name: 'Tân Phước' },
    ],
  },
  {
    code: 'TV',
    name: 'Trà Vinh',
    districts: [
      { code: 'TRA_VINH', name: 'Trà Vinh' },
      { code: 'CAU_KE', name: 'Cầu Kè' },
      { code: 'CAU_NGANG', name: 'Cầu Ngang' },
      { code: 'CHA_THANH', name: 'Châu Thành' },
      { code: 'DUYEN_HAI', name: 'Duyên Hải' },
      { code: 'TIEU_CAN', name: 'Tiểu Cần' },
      { code: 'CANG_LONG', name: 'Càng Long' },
      { code: 'TRA_CU', name: 'Trà Cú' },
    ],
  },
  {
    code: 'TQ',
    name: 'Tuyên Quang',
    districts: [
      { code: 'TUYEN_QUANG', name: 'Tuyên Quang' },
      { code: 'LAM_BINH', name: 'Lâm Bình' },
      { code: 'NA_HANG', name: 'Na Hang' },
      { code: 'CHIEM_HOA', name: 'Chiêm Hóa' },
      { code: 'HAM_YEN', name: 'Hàm Yên' },
      { code: 'YEN_SON', name: 'Yên Sơn' },
      { code: 'SON_DUONG', name: 'Sơn Dương' },
    ],
  },
  {
    code: 'VL',
    name: 'Vĩnh Long',
    districts: [
      { code: 'VINH_LONG', name: 'Vĩnh Long' },
      { code: 'BINH_MINH', name: 'Bình Minh' },
      { code: 'BINH_TAN', name: 'Bình Tân' },
      { code: 'LONG_HO', name: 'Long Hồ' },
      { code: 'MANG_THIT', name: 'Mang Thít' },
      { code: 'TAM_BINH', name: 'Tam Bình' },
      { code: 'TRA_ON', name: 'Trà Ôn' },
      { code: 'VUNG_LIEM', name: 'Vũng Liêm' },
    ],
  },
  {
    code: 'VP',
    name: 'Vĩnh Phúc',
    districts: [
      { code: 'VINH_YEN', name: 'Vĩnh Yên' },
      { code: 'PHUC_YEN', name: 'Phúc Yên' },
      { code: 'LAP_THACH', name: 'Lập Thạch' },
      { code: 'SONG_LO', name: 'Sông Lô' },
      { code: 'TAM_DAO', name: 'Tam Đảo' },
      { code: 'TAM_DUONG', name: 'Tam Dương' },
      { code: 'VINH_TUONG', name: 'Vĩnh Tường' },
      { code: 'YEN_LAC', name: 'Yên Lạc' },
    ],
  },
  {
    code: 'YB',
    name: 'Yên Bái',
    districts: [
      { code: 'YEN_BAI', name: 'Yên Bái' },
      { code: 'NGHIA_LO', name: 'Nghĩa Lộ' },
      { code: 'LUC_YEN', name: 'Lục Yên' },
      { code: 'MU_CANG_CHAI', name: 'Mù Cang Chải' },
      { code: 'TRAN_YEN', name: 'Trấn Yên' },
      { code: 'TRAM_TAU', name: 'Trạm Tấu' },
      { code: 'VAN_CHAN', name: 'Văn Chấn' },
      { code: 'VAN_YEN', name: 'Văn Yên' },
      { code: 'YEN_BINH', name: 'Yên Bình' },
    ],
  },
];

// Helper functions
export const getProvinceByCode = (code: string): Province | undefined => {
  return vietnamProvinces.find(p => p.code === code);
};

export const getDistrictsByProvinceCode = (provinceCode: string): District[] => {
  const province = getProvinceByCode(provinceCode);
  return province?.districts || [];
};

export const getProvinceName = (code: string): string => {
  const province = getProvinceByCode(code);
  return province?.name || code;
};

export const getDistrictName = (provinceCode: string, districtCode: string): string => {
  const districts = getDistrictsByProvinceCode(provinceCode);
  const district = districts.find(d => d.code === districtCode);
  return district?.name || districtCode;
};


