-- Seed script: Create dich-vu page with sections from hardcode data
-- Date: 2025-01-28
-- Description: Migrate hardcode data from frontend components to database
-- This script uses the exact HTML format generated by section editors
-- Based on: projects/inlandv-frontend/components/services/*.tsx

-- Insert or update dich-vu page
INSERT INTO pages (id, slug, title, page_type, published, meta_title, meta_description, created_at, updated_at)
VALUES (
  gen_random_uuid(),
  'dich-vu',
  'Dịch vụ',
  'static',
  true,
  'Dịch vụ - Inland Real Estate',
  'Giải pháp bất động sản công nghiệp toàn diện cho doanh nghiệp FDI – Môi giới, Tư vấn pháp lý, Hỗ trợ FDI, Thiết kế & Thi công.',
  NOW(),
  NOW()
)
ON CONFLICT (slug) DO UPDATE
SET 
  title = EXCLUDED.title,
  meta_title = EXCLUDED.meta_title,
  meta_description = EXCLUDED.meta_description,
  updated_at = NOW();

-- Insert sections for dich-vu page
DO $$
DECLARE
  dich_vu_page_id UUID;
BEGIN
  SELECT id INTO dich_vu_page_id FROM pages WHERE slug = 'dich-vu';
  
  IF dich_vu_page_id IS NOT NULL THEN
    -- 1. Hero Section
    INSERT INTO page_sections (id, page_id, section_key, name, section_type, display_order, content, images, published, created_at, updated_at)
    VALUES (
      gen_random_uuid(),
      dich_vu_page_id,
      'hero',
      'Hero Section',
      'hero',
      0,
      '<div id="hero" class="services-hero-section">
    <div class="hero-badge">Giải pháp toàn diện</div>
    <h1 class="hero-title">
      Giải Pháp Bất Động Sản Công Nghiệp
      <br />
      <span class="highlight">Toàn Diện Cho Doanh Nghiệp FDI.</span>
    </h1>
    <p class="hero-subtitle">Đồng hành trên mọi chặng đường, từ tìm kiếm đến xây dựng và phát triển.</p>
    <a href="/brochures/dich-vu.pdf" download class="hero-button">
      Tải Brochure
    </a>
  </div>',
      ARRAY[]::TEXT[],
      true,
      NOW(),
      NOW()
    )
    ON CONFLICT (page_id, section_key) DO UPDATE
    SET 
      name = EXCLUDED.name,
      content = EXCLUDED.content,
      updated_at = NOW();

    -- 2. Brokerage Section (Môi giới)
    INSERT INTO page_sections (id, page_id, section_key, name, section_type, display_order, content, images, published, created_at, updated_at)
    VALUES (
      gen_random_uuid(),
      dich_vu_page_id,
      'moi-gioi',
      'Môi giới BĐS Công nghiệp',
      'service',
      1,
      '<div id="moi-gioi" class="brokerage-section">
    <div class="section-badge">Môi giới BĐS Công nghiệp</div>
    <h2 class="section-title">Thuê / Mua <span class="highlight">Hiệu Quả</span></h2>
    <p class="section-subtitle">Giải pháp tối ưu kết nối nhu cầu doanh nghiệp FDI với nguồn cung nhà xưởng & đất công nghiệp chất lượng cao.</p>
    <div class="brokerage-content">
      <div class="advantages-column">
        <h3>Ưu điểm</h3>
        <ul><li>Tiếp cận nhanh danh mục nhà xưởng & đất công nghiệp chất lượng</li><li>Quy trình minh bạch, pháp lý rõ ràng</li><li>Tư vấn tối ưu chi phí & thời gian thuê/mua</li><li>Hỗ trợ đàm phán & ký kết hợp đồng an toàn</li></ul>
      </div>
      <div class="process-column">
        <h3>Quy trình</h3>
        <ol><li><span class="step-number">1</span>Tiếp nhận nhu cầu & tiêu chí</li><li><span class="step-number">2</span>Khảo sát & đề xuất địa điểm phù hợp</li><li><span class="step-number">3</span>Pháp lý & thẩm định điều kiện</li><li><span class="step-number">4</span>Đàm phán & ký kết</li><li><span class="step-number">5</span>Bàn giao & hỗ trợ vận hành đầu kỳ</li></ol>
      </div>
      <div class="diverse-areas-column">
        <h3>Diện tích đa dạng</h3>
        <ul><li>Đa dạng diện tích từ vài trăm m² đến hàng chục nghìn m²</li><li>Nhiều loại hình: nhà xưởng xây sẵn, đất nền, kho bãi</li><li>Phân bố tại các KCN trọng điểm: Long An, Bình Dương, Bình Phước, Tây Ninh</li><li>Đáp ứng mọi nhu cầu từ sản xuất nhỏ đến quy mô lớn</li></ul>
      </div>
    </div>
    <div class="categories-grid">
      <div class="category-item">
      <div class="category-icon">🏭</div>
      <h3>Nhà xưởng xây sẵn</h3>
      <p>Tiết kiệm thời gian, sẵn sàng vận hành</p>
    </div>
      <div class="category-item">
      <div class="category-icon">📦</div>
      <h3>Đất công nghiệp</h3>
      <p>Phù hợp mở rộng sản xuất dài hạn</p>
    </div>
    </div>
  </div>',
      ARRAY[]::TEXT[],
      true,
      NOW(),
      NOW()
    )
    ON CONFLICT (page_id, section_key) DO UPDATE
    SET 
      name = EXCLUDED.name,
      content = EXCLUDED.content,
      updated_at = NOW();

    -- 3. Legal Investment Section (Pháp lý)
    INSERT INTO page_sections (id, page_id, section_key, name, section_type, display_order, content, images, published, created_at, updated_at)
    VALUES (
      gen_random_uuid(),
      dich_vu_page_id,
      'phap-ly',
      'Tư vấn Pháp lý & Đầu tư',
      'service',
      2,
      '<div id="phap-ly" class="legal-investment-section">
    <div class="section-badge">Tư vấn Pháp lý & Đầu tư</div>
    <h2 class="section-title">An Toàn <span class="highlight">Pháp Lý</span></h2>
    <p class="section-subtitle">Dịch vụ chuyên sâu đảm bảo dự án đầu tư tuân thủ đúng quy định, tối ưu chi phí & thời gian vận hành.</p>
    <div class="legal-content">
      <div class="services-column">
        <h3>Dịch vụ cụ thể</h3>
        <div class="services-list">
    <div class="service-item">
      <div class="service-icon">📄</div>
      <h3>Giấy phép đầu tư</h3>
      <p>Tư vấn hồ sơ & tối ưu thời gian xử lý</p>
    </div>
    <div class="service-item">
      <div class="service-icon">🔨</div>
      <h3>Thủ tục xây dựng</h3>
      <p>Hỗ trợ xin giấy phép xây dựng & PCCC</p>
    </div>
    <div class="service-item">
      <div class="service-icon">📜</div>
      <h3>Hợp đồng & pháp chế</h3>
      <p>Rà soát rủi ro, đảm bảo tính pháp lý</p>
    </div>
    <div class="service-item">
      <div class="service-icon">🛡️</div>
      <h3>Tuân thủ & bảo hộ</h3>
      <p>Đảm bảo hoạt động phù hợp quy định hiện hành</p>
    </div>
  </div>
      </div>
      <div class="benefits-column">
        <h3>Lợi ích</h3>
        <ul><li>Giảm thiểu rủi ro pháp lý ngay từ đầu</li><li>Tối ưu thời gian triển khai dự án</li><li>Đảm bảo tính hợp lệ hồ sơ & chứng từ</li><li>Đồng hành xuyên suốt trong và sau cấp phép</li></ul>
      </div>
      <div class="summary-column">
        <h3>Kết quả mang lại</h3>
        <p>Đảm bảo dự án vận hành hợp pháp, hạn chế tối đa rủi ro trong các giai đoạn tiếp theo: xây dựng, mở rộng, chuyển giao.</p>
        <div class="stats-grid">
    <div class="stat-item">
      <div class="stat-value">100% Hồ sơ đạt chuẩn</div>
      <div class="stat-label">Được thẩm định trước khi nộp</div>
    </div>
    <div class="stat-item">
      <div class="stat-value">Giảm 30% thời gian xử lý</div>
      <div class="stat-label">So với tự triển khai</div>
    </div>
    <div class="stat-item">
      <div class="stat-value">Tư vấn liên tục</div>
      <div class="stat-label">Trong & sau cấp phép đầu tư</div>
    </div>
  </div>
      </div>
    </div>
  </div>',
      ARRAY[]::TEXT[],
      true,
      NOW(),
      NOW()
    )
    ON CONFLICT (page_id, section_key) DO UPDATE
    SET 
      name = EXCLUDED.name,
      content = EXCLUDED.content,
      updated_at = NOW();

    -- 4. FDI Support Section
    INSERT INTO page_sections (id, page_id, section_key, name, section_type, display_order, content, images, published, created_at, updated_at)
    VALUES (
      gen_random_uuid(),
      dich_vu_page_id,
      'fdi',
      'Hỗ trợ FDI',
      'service',
      3,
      '<div id="fdi" class="fdi-support-section">
    <div class="section-badge">Hỗ trợ FDI</div>
    <h2 class="section-title">Vận Hành <span class="highlight">Ổn Định</span> Ngay Từ Ngày Đầu</h2>
    <p class="section-subtitle">Gói dịch vụ toàn diện giúp doanh nghiệp FDI giảm ma sát khi triển khai hoạt động sản xuất và xây dựng đội ngũ tại Việt Nam.</p>
    <div class="pillars-grid">
    <div class="pillar-item">
      <div class="pillar-icon">👥</div>
      <h3>Tuyển dụng địa phương</h3>
      <p>Kết nối nguồn nhân lực phù hợp ngành & văn hoá.</p>
    </div>
    <div class="pillar-item">
      <div class="pillar-icon">💼</div>
      <h3>Nhân sự & hành chính</h3>
      <p>Thiết lập quy trình nội bộ, hồ sơ lao động, bảo hiểm.</p>
    </div>
    <div class="pillar-item">
      <div class="pillar-icon">🌐</div>
      <h3>Hội nhập văn hoá</h3>
      <p>Đào tạo thích ứng môi trường làm việc & pháp luật VN.</p>
    </div>
    <div class="pillar-item">
      <div class="pillar-icon">🤝</div>
      <h3>Đời sống doanh nghiệp</h3>
      <p>Hoạt động gắn kết, CSR, phúc lợi cơ bản.</p>
    </div>
  </div>
    <div class="fdi-content">
      <div class="services-column">
        <h3>Danh mục hỗ trợ</h3>
        <ul><li>Xây dựng cơ cấu tổ chức ban đầu</li><li>Thiết lập thang bảng lương & chính sách phúc lợi</li><li>Tuyển dụng vị trí quản lý & kỹ thuật trọng yếu</li><li>Soạn thảo nội quy lao động & thỏa ước</li><li>Đào tạo an toàn lao động cơ bản</li><li>Tổ chức định hướng nhân viên mới (onboarding)</li><li>Thiết lập kênh truyền thông nội bộ</li><li>Tư vấn chiến lược nhân sự 12 tháng đầu</li></ul>
      </div>
      <div class="outcomes-column">
        <h3>Kết quả</h3>
        <div class="outcomes-grid">
    <div class="outcome-item">
      <div class="outcome-value">30%+</div>
      <div class="outcome-label">Rút ngắn thời gian tuyển</div>
    </div>
    <div class="outcome-item">
      <div class="outcome-value">100%</div>
      <div class="outcome-label">Hồ sơ lao động đạt chuẩn</div>
    </div>
    <div class="outcome-item">
      <div class="outcome-value">24/7</div>
      <div class="outcome-label">Hỗ trợ hành chính</div>
    </div>
    <div class="outcome-item">
      <div class="outcome-value">0</div>
      <div class="outcome-label">Sự cố pháp lý phát sinh</div>
    </div>
  </div>
      </div>
      <div class="summary-column">
        <h3>Tại sao quan trọng</h3>
        <p>12 tháng đầu là giai đoạn quyết định hiệu suất dài hạn. Inland đồng hành giúp doanh nghiệp thiết lập nền tảng nhân sự, văn hoá & quy trình chuẩn thay vì tự xử lý manh mún gây phát sinh rủi ro.</p>
        <div class="stats-grid">
    <div class="stat-item">
      <div class="stat-value">Giảm 40% chi phí sai sót</div>
      <div class="stat-label">So với thiếu chuẩn hoá ban đầu</div>
    </div>
    <div class="stat-item">
      <div class="stat-value">Thiết lập nhanh hệ thống HR</div>
      <div class="stat-label">Quy trình, biểu mẫu, hồ sơ</div>
    </div>
    <div class="stat-item">
      <div class="stat-value">Nâng cao giữ chân nhân sự</div>
      <div class="stat-label">Onboarding bài bản & phúc lợi rõ ràng</div>
    </div>
  </div>
      </div>
    </div>
  </div>',
      ARRAY[]::TEXT[],
      true,
      NOW(),
      NOW()
    )
    ON CONFLICT (page_id, section_key) DO UPDATE
    SET 
      name = EXCLUDED.name,
      content = EXCLUDED.content,
      updated_at = NOW();

    -- 5. Design Construction Section
    INSERT INTO page_sections (id, page_id, section_key, name, section_type, display_order, content, images, published, created_at, updated_at)
    VALUES (
      gen_random_uuid(),
      dich_vu_page_id,
      'thiet-ke-thi-cong',
      'Thiết kế & Thi công',
      'service',
      4,
      '<div id="thiet-ke-thi-cong" class="design-construction-section">
    <div class="section-badge">Thiết kế & Thi công</div>
    <h2 class="section-title">Triển Khai <span class="highlight">Chuẩn Hoá</span> & Tối ưu Dòng Chảy Sản Xuất</h2>
    <p class="section-subtitle">Quy trình tích hợp từ khảo sát đến vận hành đầu kỳ đảm bảo hiệu suất và khả năng mở rộng trong tương lai.</p>
    <div class="phases-grid">
    <div class="phase-item">
      <div class="phase-icon">📋</div>
      <h3>Khảo sát nhu cầu</h3>
      <p>Phân tích công năng, sản lượng, quy chuẩn kỹ thuật.</p>
    </div>
    <div class="phase-item">
      <div class="phase-icon">📏</div>
      <h3>Thiết kế concept</h3>
      <p>Phác thảo sơ bộ layout, tối ưu dòng chảy sản xuất.</p>
    </div>
    <div class="phase-item">
      <div class="phase-icon">📚</div>
      <h3>Thiết kế kỹ thuật</h3>
      <p>Bản vẽ chi tiết kiến trúc, kết cấu, MEP, phòng cháy.</p>
    </div>
    <div class="phase-item">
      <div class="phase-icon">🔨</div>
      <h3>Thi công & giám sát</h3>
      <p>Quản lý tiến độ, chất lượng, an toàn lao động.</p>
    </div>
    <div class="phase-item">
      <div class="phase-icon">🏢</div>
      <h3>Nghiệm thu & bàn giao</h3>
      <p>Kiểm tra thông số cuối cùng & hoàn thiện hồ sơ.</p>
    </div>
    <div class="phase-item">
      <div class="phase-icon">✅</div>
      <h3>Vận hành đầu kỳ</h3>
      <p>Tối ưu vận hành ban đầu, điều chỉnh thực tế.</p>
    </div>
  </div>
    <div class="design-content">
      <div class="advantages-column">
        <h3>Lợi thế tích hợp</h3>
        <ul><li>Tối ưu chi phí vòng đời nhà xưởng</li><li>Đảm bảo tiêu chuẩn an toàn & tuân thủ</li><li>Giảm thời gian điều chỉnh phát sinh</li><li>Tăng hiệu suất vận hành ngay sau bàn giao</li></ul>
      </div>
      <div class="quality-column">
        <h3>Kiểm soát chất lượng</h3>
        <p>Áp dụng checklist chuẩn quốc tế cho từng hạng mục thi công: vật liệu, an toàn, nghiệm thu. Hạn chế lỗi lặp lại và chi phí sửa đổi.</p>
        <div class="quality-stats-grid">
    <div class="stat-item">
      <div class="stat-value">98%</div>
      <div class="stat-label">Đúng tiến độ</div>
    </div>
    <div class="stat-item">
      <div class="stat-value">&lt;4%</div>
      <div class="stat-label">Phát sinh điều chỉnh</div>
    </div>
    <div class="stat-item">
      <div class="stat-value">0</div>
      <div class="stat-label">Sự cố an toàn nghiêm trọng</div>
    </div>
    <div class="stat-item">
      <div class="stat-value">100%</div>
      <div class="stat-label">Nghiệm thu đạt chuẩn</div>
    </div>
  </div>
      </div>
      <div class="interlink-column">
        <h3>Kết nối INTERLINK</h3>
        <p>Tích hợp dữ liệu thiết kế với hệ thống quản lý sản xuất & vận hành giúp giảm thời gian chuyển giao sau bàn giao xây dựng.</p>
        <ul><li>Đồng bộ thông số thiết bị</li><li>Chuẩn hoá layout digital twin</li><li>API kết nối hệ thống ERP/MES</li><li>Theo dõi bảo trì từ ngày đầu</li></ul>
      </div>
    </div>
  </div>',
      ARRAY[]::TEXT[],
      true,
      NOW(),
      NOW()
    )
    ON CONFLICT (page_id, section_key) DO UPDATE
    SET 
      name = EXCLUDED.name,
      content = EXCLUDED.content,
      updated_at = NOW();

    RAISE NOTICE 'Successfully seeded dich-vu page with 5 sections';
  ELSE
    RAISE NOTICE 'dich-vu page not found, skipping section inserts';
  END IF;
END $$;
